apiVersion: v1
kind: Service
metadata:
  name: node-to-nginx
spec:
  type: NodePort
  selector:
    app: node-to-nginx
  ports:
    - port: 3333
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-to-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-to-nginx
  template:
    metadata:
      labels:
        app: node-to-nginx
    spec:
      containers:
        - name: node-to-nginx
          image: bradypp/node-to-nginx
          resources:
            limits:
              memory: '128Mi'
              cpu: '250m'
          ports:
            - containerPort: 3000
